### ISSUE TITLE
Advanced Thrown Weapons seems bugged

### ISSUE THREAD

**Issue by Far2Casual** [JDCalvert/FVTT-PF2e-Ranged-Combat#129] opened 2023-07-01 11:41 UTC
You have one Throwing Knife held.
![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/63196064/b3b9fa86-3190-4dac-9558-033555165b80)

If you throw it, it removes one item held, creates a 0-item stack that is **worn**, not dropped.
![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/63196064/edc6164d-9fd4-4c44-811c-f7bfa642d537)
![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/63196064/85d02784-8e00-4970-bc40-eccfae4b8935)

When drawing a weapon from that new stack.
![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/63196064/10a09c51-d46b-4cbe-ba59-c17a1de15535)

It does not increase the amount of held items and deletes the stack, so you're stuck with 0 items held.
![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/63196064/ef1da39f-6bd3-44ea-ad34-8b8357521b21)

You can't fire again unless you manually edit the amount of items held.
![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/63196064/e3839cd7-f6d3-4131-87f0-b7ff5927eb92)

**Comment by JDCalvert** [comment] 2023-07-03 12:04
It looks like this is due to a change in how Foundry functions around the `updateEmbeddedDocuments` function. In v10, you could update the same object multiple times in one call, and each update would happen sequentially. Now, it seems, only the final update to that object takes effect and the others are lost.

I've fixed this in version 4.0.1 by merging the updates if there's more than one for the same item.

**Comment by Far2Casual** [comment] 2023-07-05 06:44
Thank you !

Unfortunately, it caused another bug: after throwing the weapon, the weapon is not considered as having been thrown and the player can attack with it again without having to draw it back.

**Comment by JDCalvert** [comment] 2023-07-06 08:51
I'm afraid I'm not seeing the behaviour you're talking about, everything looks to be working okay for me on the latest version. It might be that the earlier bug messed up some of the data that the module uses for moving items about stacks. Can you try deleting the weapon (all stacks of it) from your character and adding them again?

**Comment by Far2Casual** [comment] 2023-07-07 08:56
Yep, still having it now (Foundry V11.305, PF2E 5.1.1, Ranged Combat 4.0.1).

1. I gave a new Hatchet to the character
![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/63196064/ca846666-4044-4b97-8c33-db3d035df6a0)

2. I fire with it. A new Hatchet is created.
![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/63196064/9e414aa6-7ba8-4c03-8b25-414f2d64421b)
![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/63196064/5d8a26ef-4559-4e79-8a1e-3340caa74580)

3. I can now fire with it again, fire is not prevented, another Hatchet is created.
![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/63196064/5b460a01-ee97-4373-a47c-1b9fecd7320f)
![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/63196064/9f00bf3a-7c87-4bf6-87cc-b8ad4f9d6d9c)

**Comment by JDCalvert** [comment] 2023-07-07 10:29
That's very strange, as that's not what I'm seeing on my end. I tried to upload a video of what I'm seeing but GitHub won't cooperate.

I'm afraid all I can suggest at the moment is:
* Fresh install of the module.
* Try it on a fresh world with no other modules enabled, in case something else is messing with it.

**Comment by Far2Casual** [comment] 2023-07-09 18:06
I'm afraid the same happens on a completely new world with 0 modules and fresh actors. Here I've just created a new PC with a Throwing Knife, I attacked twice, and:
![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/63196064/b7866911-3648-4ad2-aeb1-6868c18d9517)
![image](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/assets/63196064/0e45b97d-add5-4f91-bad7-02bcd941b3eb)

**Comment by JDCalvert** [comment] 2023-07-09 20:57
One more idea. Are you on a slow computer or browser? Because of the way item creation works, the module has to create the new stack and then update it. If you attack twice quickly this can interrupt it. If you only attack once and give it a few seconds, does it eventually become "dropped"?

**Comment by Far2Casual** [comment] 2023-07-10 08:31
My first tests were directly on my Raspberry PI server which hosts my regular games, so I was using a browser (on my gaming computer).

The most recent test (new install, new world, new everything) was made on the Windows Foundry client, not at all on a slow computer.

**Comment by Pyroman2xxx** [comment] 2023-08-22 02:27
I am seeing this exact same issue. Here is an error in the console log at the time that it happens:
Foundry VTT | Created Item with id [ykxVOcihtVOjM4VS] in parent Actor [sDC0eYSmyV6MwhOD]
commons.js:4418

Uncaught (in promise) Error: undefined. undefined id [ykxVOcihtVOjM4VS] does not exist in the EmbeddedCollection collection.
[Detected 1 package: pf2e-ranged-combat]
    at EmbeddedCollection.get (commons.js:4418:38)
    at #preUpdateDocumentArray (foundry.js:13562:30)
    at ClientDatabaseBackend._updateDocuments (foundry.js:13366:73)
    at ClientDatabaseBackend.update (commons.js:8586:19)
    at async Proxy.updateDocuments (commons.js:7910:23)
    at async Updates.handleUpdates (utils.js:55:34)
    at async createNewStack (change-carry-type.js:164:9)

**Comment by JDCalvert** [comment] 2023-08-22 15:48
@Pyroman2xxx something very strange must be happening for that log to come out. The way the module works is to first create the new stack (which we can see as the first log), but they're _always_ created as worn. Because of this, we immediately update the stack to have the correct equipped state and quantity.

To be able to update the stack, we actually wait for it to finish being created, and then only try to do the update if it was successful. The second log is referencing the same ID that was just created, so it thinks that the new stack isn't on the actor even though we've had confirmation that it's been successfully created.

What Foundry version, module version, and browser are you running on? I've been completely unable to replicate this while running through Chrome 115.0.5790.173 on Foundry 11 307 and PF2e Ranged Combat 4.0.4.

**Comment by Pyroman2xxx** [comment] 2023-08-22 18:46
I was using the actual Windows server client running Foundry 11.307, pf2e 5.3.2 and pf2e-ranged-combat 4.0.4.

Just FYI, I ran this using Chrome Version 116.0.5845.97 (Official Build) (64-bit) and the error never occurs. So it only happens when using the server client. When trying to recreate this using the browser there are no errors on the Windows server client console.

**Comment by JDCalvert** [comment] 2023-10-01 19:55
@Pyroman2xxx could you just clarify for me: the server is running using the native app, you're connected via the browser, and you see the error occur, but there are no error logs in either the client (browser) or the server?

**Comment by Pyroman2xxx** [comment] 2023-10-01 22:19
I just retested using the following:
1. Created new world with PF2e version 5.6.2 on Foundry version 11.311
2. Enabled the Ranged Combat mod and its dependency (made sure the settings use the Advanced Thrown system)
3. Added Amiri (Level 1) from the Pregenerated compendium (1 stack of 4 javelins)
4. Created Player2 and gave ownership of Amiri to it
5. Joined the game with Player2 running Chrome Version 117.0.5938.132 (Official Build) (64-bit) and selected Amiri
6. Created a new scene and added Amiri and one Adept from the compendium to it
7. Threw a javelin at the Adept with the Chrome client player
8. No errors in Chrome and none on the server and ended with a stack of 4 javelins equipped and one stack of zero javelins not equipped.
9. Threw a javelin with Amiri at the Adept on the server client
10. End up with still a stack of 4 javelins equipped and a second stack of zero javelins unequipped (viewed on both servers)
11. No error on the Chrome client but the following error on the server client (Proton):

```
caught (in promise) Error: undefined. undefined id [lG1InNXbz7NghDgg] does not exist in the EmbeddedCollection collection.
[Detected 1 package: pf2e-ranged-combat]
    at EmbeddedCollection.get (commons.js:4499:38)
    at #preUpdateDocumentArray (foundry.js:13585:30)
    at ClientDatabaseBackend._updateDocuments (foundry.js:13389:73)
    at ClientDatabaseBackend.update (commons.js:8672:19)
    at async Proxy.updateDocuments (commons.js:7996:23)
    at async Updates.handleUpdates (utils.js:55:34)
    at async createNewStack (change-carry-type.js:164:9)
```

**Comment by Cosmic-Lattee** [comment] 2023-11-05 21:19
I just wanted to confirm that this error is also happening to me as a GM and my players as well.

**Comment by JDCalvert** [comment] 2023-12-27 00:06
I _finally_ figured this out. @Pyroman2xxx your replication steps were very helpful. The bug seems to only occur when a token is targeted. I have no idea why - from what I've seen, it should _never_ have worked.

Because of the way the item is created, I have to create it and then update it. I was also updating the other items in the "group", but I was using the retrieved actor from before the creation to run the update, and that actor doesn't have the stack.

The solution was simply to use the actor from the newly-created item (which is returned from the call to create the item) as the update actor, and the problem is **finally** solved!

**Closed by JDCalvert** 2023-12-27 00:06 UTC
