### ISSUE TITLE
Could you make a macro for Attack Roll on Aid?

### ISSUE THREAD

**Issue by Bomberman1988** [JDCalvert/FVTT-PF2e-Ranged-Combat#165] opened 2024-02-19 19:51 UTC
That can work for anyone but much more frequently for the Gunslinger and its amazing fear [Fake Out](https://2e.aonprd.com/Feats.aspx?ID=3161) that allows the user to make an Attack Roll for an Aid check.
The thing is - if we do that we spend a bullet, having to recharge it after (which is even more annoying with Repeating and Capacity weapons, so would you mind making a macro for Attack Roll so we can roll Aid, or at least show me how to do it cuz I've no clue.

**Comment by JDCalvert** [comment] 2024-02-19 20:56
I've just released 5.1.1 which has added a bit of code to skip ammunition processing after firing. You can utilise this on Fake Out by adding the following rules to it:

```
{
  "key": "RollOption",
  "option": "skip-use-ammunition",
  "toggleable": true,
  "value": false
}
```

```
{
  "key": "RollOption",
  "option": "fake-out-circumstance-bonus",
  "label": "Damaged target since start of last turn",
  "toggleable": true,
  "disabledIf": [
    {
      "not": "use-ammunition:false"
    }
  ],
  "disabledValue": false,
  "value": true
}
```

```
{
  "key": "FlatModifier",
  "selector": "attack-roll",
  "value": 1,
  "predicate": [
    "fake-out-circumstance-bonus",
    {
      "or": [
        "item:group:firearm",
        "item:group:crossbow"
      ]
    }
  ],
  "type": "circumstance"
}
```

When I have a bit more time, I'll add some code to automatically add these rules to Fake Out, but I don't have time right now.

**Comment by xyzzy42** [comment] 2024-03-05 00:21
I noticed this same problem with another system that wants to get the result of what an attack role would do, without actually making an attack.  Came to report the issue, but it's basically a dupe of this one.

The pf2e system itself has an option for this, `consumeAmmo`, that can be set to false in the attack roll params to prevent ammo consumption.  Typically also combined with `createMessage: false`.  It was added here https://github.com/foundryvtt/pf2e/pull/5658

This works with the pf2e system ammo consumption, it entirely skips the action's `consumeAmmo()` method call, but this module doesn't use the consumeAmmo hook to actually use the ammo and so it doesn't respect the roll parameter.

So instead of creating a custom roll option that only works with this module, maybe it would be better if this module used the existing parameter, so that anything that doesn't want to consume ammo can work with both this module and the base pf2e system.

**Comment by JDCalvert** [comment] 2024-06-15 23:10
The module already disables `consumeAmmo` for all strikes so it can take care of ammunition consumption itself.

I've added automation to this feat - posting it to chat with a target selected will roll an attack roll against the target, not trigger any of the post-roll processing from the module (including ammunition consumption) and post a message saying what bonus/penalty was granted.

**Closed by JDCalvert** 2024-06-15 23:10 UTC

**Comment by Bomberman1988** [comment] 2024-06-18 15:58
I just saw it and maaaan that's beautiful! Thank you very much, wonderful
job! 👏👏👏👏👏👏👏👏👏👏👏👏
