### ISSUE TITLE
Feature Request: Support for gunslingers feats and features

### ISSUE THREAD

**Issue by LeandroMartinelli** [JDCalvert/FVTT-PF2e-Ranged-Combat#45] opened 2022-05-06 14:20 UTC
Feats and features for gunslingers (and some for other classes too) like Running Reload, Reloading Strike, Raconteur's Reload, etc...

**Comment by JDCalvert** [comment] 2022-05-06 22:36
I'm afraid this is a duplicate of #24 (there's no good way of making past issues visible without simply leaving them open). As I said on the other issue, I don't think this is really in scope for the module, since the gunslingers reloads are generally just performing two actions for the price of one - the reload subbordinate action is unchanged. The easiest thing to do would be to make a macro that posts the gunslinger's reload action and then runs the reload macro.

**Closed by JDCalvert** 2022-05-06 22:36 UTC
Labels: enhancement
