### ISSUE TITLE
NPC Weapon Loadout does not detect ammunition

### ISSUE THREAD

**Issue by AlastarOG** [JDCalvert/FVTT-PF2e-Ranged-Combat#106] opened 2023-02-07 18:35 UTC
When using the reload macro, load magazine macro or npc weapon loadout macro, the ammunition in the NPC's inventory is not detected as ammunition, and therefore cannot be loaded.

Tried with multiple weapons and ammo.

Had to uninstall module because of that.

**Comment by JDCalvert** [comment] 2023-02-08 14:42
Looks like this was caused by a recent change to the PF2e system. Fixed in version 3.6.0!

**Comment by cbuffett** [comment] 2023-02-24 00:09
This appears to be broken again on version 4.8.0 of PF2e. No way to specify ammunition for a ranged weapon and a message saying the ranged weapon isn't loaded is shown when attempting to attack.

**Comment by JDCalvert** [comment] 2023-02-24 10:33
Hi @cbuffett, I've just had a little test of this and it appears to be working for me. Could you please give replication steps, if possible with a new world and only the PF2e Ranged Combat module (and dependencies) active?

**Comment by cbuffett** [comment] 2023-02-24 18:35
I realized I was missing some info that was down towards the bottom of the README on how to handle NPCs vs PCs. This is working correctly for me now.

**Comment by JDCalvert** [comment] 2023-02-24 20:32
That great! Glad it's working

**Closed by JDCalvert** 2023-02-24 20:32 UTC
